export const data = [
    'main worker income see scientific try game wood joined captain mood bag while heading acres basis out grade cheese secret found more combine bear',
    'industry mine larger manner occasionally various collect orange shelter part jungle does broad youth weigh machine quietly community cook touch second event remain control',
    'saved recent satellites body shop greatly continent buffalo team badly useful increase some find careful provide tail charge food production evidence action customs education',
    'dollar bend brass important golden feet excitement spend fighting middle love solid call loose went smile worth tomorrow plant route chest high favorite prevent',
    'night magic learn difficulty clothing knew danger simple solid musical trace refused swam form port local dawn third thick solve molecular pine sea globe',
    'difficulty leaving pupil blood provide storm fish century bear deeply purpose pocket art numeral page call edge dirt nervous cowboy moment strange whistle them',
    'have speak scale lion stepped said floor burn thirty receive begun furniture classroom shoulder information basis top kept additional pool attention lead music caught',
    'sugar exactly shoe nothing grade tears promised year party syllable duck root continent pink organization using coach tank tomorrow mental on said thick push',
    'trade reader see wolf exciting mill handsome independent forth coat clay fish please knowledge purpose by greatest therefore calm stove go opinion kitchen composition',
    'press iron feet flame aside line disease facing map by smaller nearly wind knowledge same captain age find worry act modern excitement sent important',
    'fight man throat fourth supper brother change gasoline according examine fuel nor principal chose below palace construction type western simplest skill tune frozen union',
    'record sign equipment heat single steel possibly seed flow front cannot exact toy pony brown helpful create wash eleven opposite fine gray string river',
    'guide leaf test manner well valuable forgot labor addition fallen whatever home parts nor bare vertical once share they neck month involved noted paragraph',
    'construction term slope local flame play edge piece point great improve answer shore wave cave medicine never lungs load popular blow land dog friendly',
    'exist announced hat review consonant disease small important studied claws hit judge shall visit rising drink alike globe rock purple age answer five someone',
    'wall forty children letter large fox arrow telephone hearing first no some nine massage return swimming grew yesterday surprise organization several note quiet village',
    'property spin score fire meat run tonight throw stuck slide enemy large why drawn medicine ran must particularly promised carbon simplest late reason feed',
    'method west onto unless whether cent active tin usually tube opposite keep safe accident cowboy reach shoulder flow memory ocean discussion nodded eventually lion',
    'rocket appearance already gravity managed rose oldest tropical organization something recently railroad rhythm distant method land connected exercise opposite fireplace late money imagine paragraph',
    'year farm curve exactly shoe sleep pupil jar earn wood four beside pine felt environment shown film pitch tide should outer finally snow trunk',
    'slight solid salt harder buy nothing traffic how swimming program stared fighting greater lovely catch sleep interior put scale accept composed pass paid cool',
    'barn both pilot these ear nearby had examine potatoes busy policeman thank remarkable snake settle improve as took field man lot suddenly trunk again',
    'shop deep column image nearly individual about touch operation syllable excitement began captain rich hundred getting relationship slope rather fed progress bill field serious',
    'anyway prove certain black fully bow afraid purpose jar breathe exist instant silk sheet few inch rear sad island draw burn lift religious story'
]